### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by cystbear** [huffman/twilio_erlang#11]
Does this project still alive?
Currently build is failing :cry: 

ping @huffman

**Comment by huffman** [comment]
@cystbear I'm not currently using or developing this, but I'd be happy to review + merge a PR if you have a fix :)

**Comment by huffman** [comment]
@hypernumbers Might also have some input, he's most recently made contributions

**Comment by cystbear** [comment]
there are a lot of forks, so I will analyze the code and grab that stuff that I need.
Or even create my own, for sure based on your one :)

WIll wait @hypernumbers  answer

**Comment by gordonguthrie** [comment]
I don't really use it any more...

**Comment by shlokspeare** [comment]
@cystbear ,can you recommend some forks that I can use? have to integrate the api into my app

**Comment by cystbear** [comment]
@shlokspeare take a look this https://github.com/tapsters/etwilio it's our own repo
